# FROM waggle/plugin-base:1.1.1-base
# FROM nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04
# FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04

# w/ cudnn support
# FROM nvidia/cuda:11.6.2-cudnn8-runtime-ubuntu20.04
# Might be smaller?
FROM nvidia/cuda:11.6.2-runtime-ubuntu20.04

# FROM waggle/plugin-base:1.1.1-ml-cuda11.0-amd64


WORKDIR /app

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1

# Update GCC via REPO (perhaps you can use this hacky way to bypass the need to compile the aforementioned)
# RUN echo "deb http://archive.ubuntu.com/ubuntu jammy main" | tee /etc/apt/sources.list.d/temporary-repository.list
# RUN apt-get -y update --fix-missing && apt-get -y install --no-install-recommends \
#     build-essential \
#     python3 \
#     python3-distutils \
#     python3-pip \
#     && rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      software-properties-common \
      build-essential \
      curl && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
      python3.10 \
      python3.10-distutils \
      python3.10-venv \
      python3.10-dev && \
    rm -rf /var/lib/apt/lists/*

# RUN python3 --version && sleep 10

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1 && \
    curl -sS https://bootstrap.pypa.io/get-pip.py | python3 && \
    python3 -m pip install --upgrade pip setuptools wheel



# RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3
# RUN python3 -m pip install --upgrade pip setuptools wheel

# 11.4
# RUN python3 -m pip install --upgrade pip

# RUN pip3 install torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 --index-url https://download.pytorch.org/whl/cu118
# RUN pip3 install torch --pre --extra-index-url https://download.pytorch.org/whl/nightly/cu116
RUN pip3 install torch torchvision torchaudio --pre --extra-index-url https://download.pytorch.org/whl/nightly/cu116

RUN pip3 install -U pywaggle[all]
# RUN pip3 install --no-cache-dir git+https://github.com/waggle-sensor/pywaggle

COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

COPY ./download_model_v2.py ../
# RUN cd .. && python3 download_model_v2.py
COPY huggingface ../huggingface
# COPY huggingface /root/.cache/huggingface
COPY src .

# ENTRYPOINT ["python3", "main.py"]
ENTRYPOINT ["python3", "test_samples.py"]
# ENTRYPOINT ["bash -c 'sleep 100000'"]